---

- name: Run 'apt update'
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags: 
    - database
    - web
    - nextcloud

- import_tasks: configure_database.yml
  tags: 
    - database

- import_tasks: configure_web.yml
  become: true
  tags: 
    - web

- import_tasks: configure_nextcloud.yml
  tags: 
    - nextcloud


